package org.sample.rest.RestSampleTest.model;
// Generated Jan 14, 2016 2:54:11 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.io.Serializable;

/**
 * ClientMeasureId generated by hbm2java
 */
@Embeddable
public class ClientMeasureId implements Serializable {

	@Column(name = "CLIENT_ID", nullable = false)
	private short clientId;
	@Column(name = "CLIENT_SUB_ID", nullable = false, length = 20)
	private String clientSubId;
	@Column(name = "MEAS_SK", nullable = false)
	private short measSk;
	@Column(name = "PopulationIdentifier", nullable = false)
	private int populationIdentifier;

	public ClientMeasureId() {
	}

	public ClientMeasureId(short clientId, String clientSubId, short measSk, int populationIdentifier) {
		this.clientId = clientId;
		this.clientSubId = clientSubId;
		this.measSk = measSk;
		this.populationIdentifier = populationIdentifier;
	}

	
	public short getClientId() {
		return this.clientId;
	}

	public void setClientId(short clientId) {
		this.clientId = clientId;
	}

	
	public String getClientSubId() {
		return this.clientSubId;
	}

	public void setClientSubId(String clientSubId) {
		this.clientSubId = clientSubId;
	}

	
	public short getMeasSk() {
		return this.measSk;
	}

	public void setMeasSk(short measSk) {
		this.measSk = measSk;
	}

	
	public int getPopulationIdentifier() {
		return this.populationIdentifier;
	}

	public void setPopulationIdentifier(int populationIdentifier) {
		this.populationIdentifier = populationIdentifier;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientMeasureId))
			return false;
		ClientMeasureId castOther = (ClientMeasureId) other;

		return (this.getClientId() == castOther.getClientId())
				&& ((this.getClientSubId() == castOther.getClientSubId())
						|| (this.getClientSubId() != null && castOther.getClientSubId() != null
								&& this.getClientSubId().equals(castOther.getClientSubId())))
				&& (this.getMeasSk() == castOther.getMeasSk())
				&& (this.getPopulationIdentifier() == castOther.getPopulationIdentifier());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClientId();
		result = 37 * result + (getClientSubId() == null ? 0 : this.getClientSubId().hashCode());
		result = 37 * result + this.getMeasSk();
		result = 37 * result + this.getPopulationIdentifier();
		return result;
	}

}
