

package org.sample.rest.RestSampleTest.model;


import java.io.Serializable;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;



/**
 * ClientMeasure generated by hbm2java
 */
@Entity
@Table(name = "ClientMeasure", schema = "dbo", catalog = "ujwaltest")
@XmlRootElement
public class ClientMeasure implements Serializable{

	
	private ClientMeasureId id;
	private int populationIdentifier;
	@Column(name = "PopulationName", nullable = false, length = 100)
	private String populationName;
	@Column(name = "ClientDescription", nullable = false)
	private String clientDescription;//private Serializable clientDescription;
	@Column(name = "ClientDescriptionText", nullable = false)
	private String clientDescriptionText;//private Serializable clientDescriptionText;
	@Column(name = "DenominatorIndicator", nullable = false, length = 1)
	private char denominatorIndicator;
	@Column(name = "IsSensitiveIndicator")
	private Boolean isSensitiveIndicator;
	@Column(name = "SystemCodeIdentifier")
	private Integer systemCodeIdentifier;
	@Column(name = "InterventionsIndicator")
	private Boolean interventionsIndicator;
	@Column(name = "CareRemindersIndicator")
	private Boolean careRemindersIndicator;
	@Column(name = "IsEnabledIndicator", nullable = false)
	private boolean isEnabledIndicator;
	@Column(name = "RecordLoadDatetime", nullable = false, length = 23)
	private Date recordLoadDatetime;
	@Column(name = "RecordLastUpdateDatetime", nullable = false, length = 23)
	private Date recordLastUpdateDatetime;

	
	public ClientMeasure() {
	}

	public ClientMeasure(ClientMeasureId id, String populationName, String clientDescription,
			String clientDescriptionText, char denominatorIndicator, boolean isEnabledIndicator,
			Date recordLoadDatetime, Date recordLastUpdateDatetime) {
		this.id = id;
		this.populationName = populationName;
		this.clientDescription = clientDescription;
		this.clientDescriptionText = clientDescriptionText;
		this.denominatorIndicator = denominatorIndicator;
		this.isEnabledIndicator = isEnabledIndicator;
		this.recordLoadDatetime = recordLoadDatetime;
		this.recordLastUpdateDatetime = recordLastUpdateDatetime;
	}

	public ClientMeasure(ClientMeasureId id, String populationName, String clientDescription,
			String clientDescriptionText, char denominatorIndicator, Boolean isSensitiveIndicator,
			Integer systemCodeIdentifier, Boolean interventionsIndicator, Boolean careRemindersIndicator,
			boolean isEnabledIndicator, Date recordLoadDatetime, Date recordLastUpdateDatetime) {
		this.id = id;
		this.populationName = populationName;
		this.clientDescription = clientDescription;
		this.clientDescriptionText = clientDescriptionText;
		this.denominatorIndicator = denominatorIndicator;
		this.isSensitiveIndicator = isSensitiveIndicator;
		this.systemCodeIdentifier = systemCodeIdentifier;
		this.interventionsIndicator = interventionsIndicator;
		this.careRemindersIndicator = careRemindersIndicator;
		this.isEnabledIndicator = isEnabledIndicator;
		this.recordLoadDatetime = recordLoadDatetime;
		this.recordLastUpdateDatetime = recordLastUpdateDatetime;
	}

	
	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "clientId", column = @Column(name = "CLIENT_ID", nullable = false) ),
			@AttributeOverride(name = "clientSubId", column = @Column(name = "CLIENT_SUB_ID", nullable = false, length = 20) ),
			@AttributeOverride(name = "measSk", column = @Column(name = "MEAS_SK", nullable = false) ),
			@AttributeOverride(name = "populationIdentifier", column = @Column(name = "PopulationIdentifier", nullable = false) ) })
	public ClientMeasureId getId() {
		return this.id;
	}

	public void setId(ClientMeasureId id) {
		this.id = id;
	}

	public String getPopulationName() {
		return this.populationName;
	}



	public void setPopulationName(String populationName) {
		this.populationName = populationName;
	}

	
	public String getClientDescription() {
		return this.clientDescription;
	}

	public void setClientDescription(String clientDescription) {
		this.clientDescription = clientDescription;
	}

	
	public String getClientDescriptionText() {
		return this.clientDescriptionText;
	}

	public void setClientDescriptionText(String clientDescriptionText) {
		this.clientDescriptionText = clientDescriptionText;
	}

	
	public char getDenominatorIndicator() {
		return this.denominatorIndicator;
	}

	public void setDenominatorIndicator(char denominatorIndicator) {
		this.denominatorIndicator = denominatorIndicator;
	}

	
	public Boolean getIsSensitiveIndicator() {
		return this.isSensitiveIndicator;
	}

	public void setIsSensitiveIndicator(Boolean isSensitiveIndicator) {
		this.isSensitiveIndicator = isSensitiveIndicator;
	}

	
	public Integer getSystemCodeIdentifier() {
		return this.systemCodeIdentifier;
	}

	public void setSystemCodeIdentifier(Integer systemCodeIdentifier) {
		this.systemCodeIdentifier = systemCodeIdentifier;
	}

	
	public Boolean getInterventionsIndicator() {
		return this.interventionsIndicator;
	}

	public void setInterventionsIndicator(Boolean interventionsIndicator) {
		this.interventionsIndicator = interventionsIndicator;
	}

	
	public Boolean getCareRemindersIndicator() {
		return this.careRemindersIndicator;
	}

	public void setCareRemindersIndicator(Boolean careRemindersIndicator) {
		this.careRemindersIndicator = careRemindersIndicator;
	}

	
	public boolean isIsEnabledIndicator() {
		return this.isEnabledIndicator;
	}

	public void setIsEnabledIndicator(boolean isEnabledIndicator) {
		this.isEnabledIndicator = isEnabledIndicator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	
	public Date getRecordLoadDatetime() {
		return this.recordLoadDatetime;
	}

	public void setRecordLoadDatetime(Date recordLoadDatetime) {
		this.recordLoadDatetime = recordLoadDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	
	public Date getRecordLastUpdateDatetime() {
		return this.recordLastUpdateDatetime;
	}

	public void setRecordLastUpdateDatetime(Date recordLastUpdateDatetime) {
		this.recordLastUpdateDatetime = recordLastUpdateDatetime;
	}

}




































/*package org.sample.rest.RestSampleTest.model;


import java.io.Serializable;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;



*//**
 * ClientMeasure generated by hbm2java
 *//*
@Entity
@Table(name = "ClientMeasure", schema = "dbo", catalog = "ujwaltest")
@XmlRootElement
public class ClientMeasure{

	
	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "clientId", column = @Column(name = "CLIENT_ID", nullable = false) ),
			@AttributeOverride(name = "clientSubId", column = @Column(name = "CLIENT_SUB_ID", nullable = true, length = 20) ),
			@AttributeOverride(name = "measSk", column = @Column(name = "MEAS_SK", nullable = false) ),
			@AttributeOverride(name = "populationIdentifier", column = @Column(name = "PopulationIdentifier", nullable = false) ) })
	private ClientMeasureId id;
	@Column(name = "PopulationName", nullable = false, length = 100)
	private String populationName;
	@Column(name = "ClientDescription", nullable = false)
	private Serializable clientDescription;
	@Column(name = "ClientDescriptionText", nullable = false)
	private Serializable clientDescriptionText;
	@Column(name = "DenominatorIndicator", nullable = false, length = 1)
	private char denominatorIndicator;
	@Column(name = "IsSensitiveIndicator")
	private Boolean isSensitiveIndicator;
	@Column(name = "SystemCodeIdentifier")
	private Integer systemCodeIdentifier;
	@Column(name = "InterventionsIndicator")
	private Boolean interventionsIndicator;
	@Column(name = "CareRemindersIndicator")
	private Boolean careRemindersIndicator;
	@Column(name = "IsEnabledIndicator", nullable = false)
	private boolean isEnabledIndicator;
	@Column(name = "RecordLoadDatetime", nullable = false, length = 23)
	private Date recordLoadDatetime;
	@Column(name = "RecordLastUpdateDatetime", nullable = false, length = 23)
	private Date recordLastUpdateDatetime;

	public ClientMeasure() {
	}

//	public ClientMeasure(ClientMeasureId id, String populationName, Serializable clientDescription,
//			Serializable clientDescriptionText, char denominatorIndicator, boolean isEnabledIndicator,
//			Date recordLoadDatetime, Date recordLastUpdateDatetime) {
//		this.id = id;
//		this.populationName = populationName;
//		this.clientDescription = clientDescription;
//		this.clientDescriptionText = clientDescriptionText;
//		this.denominatorIndicator = denominatorIndicator;
//		this.isEnabledIndicator = isEnabledIndicator;
//		this.recordLoadDatetime = recordLoadDatetime;
//		this.recordLastUpdateDatetime = recordLastUpdateDatetime;
//	}
	public ClientMeasure(ClientMeasureId id, String populationName, Serializable clientDescription,
			Serializable clientDescriptionText, char denominatorIndicator, Boolean isSensitiveIndicator,
			Integer systemCodeIdentifier, Boolean interventionsIndicator, Boolean careRemindersIndicator,
			boolean isEnabledIndicator, Date recordLoadDatetime, Date recordLastUpdateDatetime) {
		this.id = id;
		this.populationName = populationName;
		this.clientDescription = clientDescription;
		this.clientDescriptionText = clientDescriptionText;
		this.denominatorIndicator = denominatorIndicator;
		this.isSensitiveIndicator = isSensitiveIndicator;
		this.systemCodeIdentifier = systemCodeIdentifier;
		this.interventionsIndicator = interventionsIndicator;
		this.careRemindersIndicator = careRemindersIndicator;
		this.isEnabledIndicator = isEnabledIndicator;
		this.recordLoadDatetime = recordLoadDatetime;
		this.recordLastUpdateDatetime = recordLastUpdateDatetime;
	}

//	@EmbeddedId
//
//	@AttributeOverrides({
//			@AttributeOverride(name = "clientId", column = @Column(name = "CLIENT_ID", nullable = false) ),
//			@AttributeOverride(name = "clientSubId", column = @Column(name = "CLIENT_SUB_ID", nullable = true, length = 20) ),
//			@AttributeOverride(name = "measSk", column = @Column(name = "MEAS_SK", nullable = false) ),
//			@AttributeOverride(name = "populationIdentifier", column = @Column(name = "PopulationIdentifier", nullable = false) ) })
	

	@Embedded
	public ClientMeasureId getId() {
		return this.id;
	}

	public void setId(ClientMeasureId id) {
		this.id = id;
	}
	

	

	public String getPopulationName() {
		return this.populationName;
	}



	public void setPopulationName(String populationName) {
		this.populationName = populationName;
	}

	
	public Serializable getClientDescription() {
		return this.clientDescription;
	}

	public void setClientDescription(Serializable clientDescription) {
		this.clientDescription = clientDescription;
	}

	
	public Serializable getClientDescriptionText() {
		return this.clientDescriptionText;
	}

	public void setClientDescriptionText(Serializable clientDescriptionText) {
		this.clientDescriptionText = clientDescriptionText;
	}

	
	public char getDenominatorIndicator() {
		return this.denominatorIndicator;
	}

	public void setDenominatorIndicator(char denominatorIndicator) {
		this.denominatorIndicator = denominatorIndicator;
	}

	
	public Boolean getIsSensitiveIndicator() {
		return this.isSensitiveIndicator;
	}

	public void setIsSensitiveIndicator(Boolean isSensitiveIndicator) {
		this.isSensitiveIndicator = isSensitiveIndicator;
	}

	
	public Integer getSystemCodeIdentifier() {
		return this.systemCodeIdentifier;
	}

	public void setSystemCodeIdentifier(Integer systemCodeIdentifier) {
		this.systemCodeIdentifier = systemCodeIdentifier;
	}

	
	public Boolean getInterventionsIndicator() {
		return this.interventionsIndicator;
	}

	public void setInterventionsIndicator(Boolean interventionsIndicator) {
		this.interventionsIndicator = interventionsIndicator;
	}

	
	public Boolean getCareRemindersIndicator() {
		return this.careRemindersIndicator;
	}

	public void setCareRemindersIndicator(Boolean careRemindersIndicator) {
		this.careRemindersIndicator = careRemindersIndicator;
	}

	
	public boolean isIsEnabledIndicator() {
		return this.isEnabledIndicator;
	}

	public void setIsEnabledIndicator(boolean isEnabledIndicator) {
		this.isEnabledIndicator = isEnabledIndicator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	
	public Date getRecordLoadDatetime() {
		return this.recordLoadDatetime;
	}

	public void setRecordLoadDatetime(Date recordLoadDatetime) {
		this.recordLoadDatetime = recordLoadDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	
	public Date getRecordLastUpdateDatetime() {
		return this.recordLastUpdateDatetime;
	}

	public void setRecordLastUpdateDatetime(Date recordLastUpdateDatetime) {
		this.recordLastUpdateDatetime = recordLastUpdateDatetime;
	}

}
*/